### ISSUE TITLE
Wrong metadata?

### ISSUE THREAD

**Issue by RGB-es** [YuanshengZhao/Garamond-Math#1]
Running 

`otfinfo -i Garamond-Math.otf`

I obtain, among other info:

`Preferred family:    TeX Gyre Termes Math`

In fact, opening the font on KDE's font viewer, it report the font name as TeX Gyre Termes Math. All other metadata seems OK (font version reported is 1.543, though).

**Comment by Stone-Zeng** [comment]
Thanks for your feedback! Fixed in 35158276d9528934a4153bb35b7f3d0c38796394.
