### ISSUE TITLE
Regression: commit d42b68b5c2e91132751339a3e0889ba180ffb09f "alg. impr:" breaks math operator spacing in the binary file.

### ISSUE THREAD

**Issue by jhanschoo** [YuanshengZhao/Garamond-Math#11]
The inter-character spacing for math operators became too wide since commit d42b68b5c2e91132751339a3e0889ba180ffb09f "alg. impr:" . I'm not sure what change has caused that but the `.otf` binaries before that commit does not have that problem.

After the commit: 
![aftercommit](https://user-images.githubusercontent.com/2254497/52172602-0567eb00-27ae-11e9-9bb5-db260538f493.png)

Before the commit:
![beforecommit](https://user-images.githubusercontent.com/2254497/52172603-07ca4500-27ae-11e9-8071-28649ba3f407.png)

edit: the CTAN version contains this bug

edit: in the commit you can also see that the spacing between "x" and the comma "," is broken. I think that was fixed in a later commit, but the spacing for math operators is still broken.

**Comment by stone-zeng** [comment]
This is because that all the alphabets' spacing has been adjusted for *variables*. "arg" etc are operator names so they should use normal *word* spacing.

With `unicode-math`, you should set `mathrm=text` and use EB Garamond as the main font. Then `mathrm` will be EB Garamond rather than Garamond Math, and the spacing will become correct.

**Comment by jhanschoo** [comment]
Sorry for opening the issue. Indeed, the problem lay in the template file I was using having a `\let\mathrm\undefined` line.

**Comment by YuanshengZhao** [comment]
Now, in the newest commit today (23Mar/2019, 4414b5c), the updated script produces almost identical metric with original EB garamond for upright glyphs (though the script still assumes mathematical useage). So I simply reset the regular upright glyphs to EB garamond ones. And `symup` and `mathrm` should be the same. 

But this version still needs more test, so be MORE careful when using this version.
