### ISSUE TITLE
Feature request: larger operators variant

### ISSUE THREAD

**Issue by cluelessnessness** [YuanshengZhao/Garamond-Math#15]
I’ve been using Garamond Math for some months now to my great pleasure. One thing I’ve found, however, is that operators and relations like ∪, +, = etc. are a little small with respect to other founts, and I think it makes equations a little bit harder to read.  Would it be possible — if it’s not too much work — to have a stylistic set where these are a little larger? 

Compare the images below: the first one has the same line first in Garamond Math then in Latin Modern Math. You’ll notice that ×, ∪ and = are ever so slightly larger in the second line.  The symbols could even be a little larger, as in the second image taken from an XVIIIᵗʰ-century book.

![](https://i.imgur.com/kt1ry8Y.png)

![](https://www.researchgate.net/profile/Daniel_Chazan/publication/284031139/figure/fig1/AS:648246624010240@1531565447784/A-list-of-rules-in-an-eighteenth-century-algebra-text-book-Ward-1724-p-40.png)

**Comment by stone-zeng** [comment]
cf. alif-type/libertinus#63, firamath/firamath#39.

**Comment by YuanshengZhao** [comment]
I do not think a new stylistic set is necessary -- just modifying the current glyph is better. 
But please give me some time as I have beem very busy recently. Also it might take some effort to make everything looks consistent.

**Comment by cluelessnessness** [comment]
The current symbols look perfectly reasonable for prose-based arithmetic — perhaps consider keeping them as an additional stylistic set.  Take as long as you need ;)

**Comment by YuanshengZhao** [comment]
The new symbols are in `ss11`. I will leave this issue open until (I think) the symbols are complete and consistent.
![image](https://user-images.githubusercontent.com/37881856/63114732-84957180-bfd0-11e9-9cfb-3cf4c077e13b.png)
![image](https://user-images.githubusercontent.com/37881856/63114765-92e38d80-bfd0-11e9-9ccd-ee9e6f309401.png)
![image](https://user-images.githubusercontent.com/37881856/63114779-9f67e600-bfd0-11e9-8754-8a0d6b6eb285.png)

**Comment by cluelessnessness** [comment]
Sorry if this is a silly question, but has the `.otf` file been updated with the new operators?

Thank you

**Comment by stone-zeng** [comment]
Not yet (you may check it at this [link](https://github.com/YuanshengZhao/Garamond-Math/blob/master/Garamond-Math.otf), it's still at 0c0f55c).

**Comment by cluelessnessness** [comment]
I see, thank youAm 06.09.2019 11:19 vorm. schrieb Xiangdong Zeng <notifications@github.com>:Not yet (you may check it at this link, it's still at 0c0f55c).
