### ISSUE TITLE
Where can I download an out-of-the-box version of font?

### ISSUE THREAD

**Issue by perpi** [YuanshengZhao/Garamond-Math#17]
Hi; How can I find a otf/ttf/woff version of the font? I'm not familiar with compiling the font from scratch
thanks.

**Comment by ArchangeGabriel** [comment]
There is one https://github.com/YuanshengZhao/Garamond-Math/blob/master/Garamond-Math.otf. It might not always be up-to-date, but it currently is as a matter of facts. ;)

**Comment by YuanshengZhao** [comment]
Yes, there is an `otf` file in the repository. Other formats like `ttf` are currently not available.
