### ISSUE TITLE
Equation accents issue

### ISSUE THREAD

**Issue by DarkleSparkle** [YuanshengZhao/Garamond-Math#20]
Word math equation accents not "active" (when entering a long expression, the accents are not covering the entire formula, unlike overbars). I've used the .otf file version.

<img width="324" alt="Screenshot 2020-05-13 at 23 47 02" src="https://user-images.githubusercontent.com/65314807/81869278-0e7c6600-9574-11ea-968d-763e6e9970a9.png">

<img width="107" alt="Screenshot 2020-05-13 at 23 43 40" src="https://user-images.githubusercontent.com/65314807/81869030-9ca41c80-9573-11ea-8bbe-f5091fa3970d.png">

**Comment by YuanshengZhao** [comment]
This is because there is no such long glyphs. It should have been fixed in the latest version.
![image](https://user-images.githubusercontent.com/37881856/83223905-10226c80-a1b7-11ea-8cf7-9b06f7b19705.png)

**Comment by DarkleSparkle** [comment]
Works perfectly now, thank you ;)
