### ISSUE TITLE
feature request: semibold variant

### ISSUE THREAD

**Issue by itzsimpl** [YuanshengZhao/Garamond-Math#4]
I really like what you are doing and I was wandering if it would be possible to integrate also semibold variants. As the visual weight of the Garamond font is light and this lightness together with the flow of the glyph curves represents a major part of Garamond's beauty, I find the included bold version too pronounced (too contrasting).

**Comment by YuanshengZhao** [comment]
I have added the semi bold variants, which can be called by using `StylisticSet=4`. However, there is still a lot of work to do on metric and I will update the `.otf` once they are finished.

**Comment by itzsimpl** [comment]
Great work! Would it be possible to add also the other variants in a similar fashion, i.e. medium and extra bold. This would give the user the option to choose the version he likes best.

**Comment by Stone-Zeng** [comment]
@itzsimpl For medium and extra bold, adding another weights (I mean adding `garamond-math-medium.otf`, `garamond-math-bold.otf` etc) may be better. But it could be a hard job.

**Comment by itzsimpl** [comment]
I assume that to create variants `garamond-math-medium.otf` and `garamond-math-extra bold.otf` one would need to make medium/extra bold variants of multiple other glyphs (math symbols). Hence a really hard job. My request was more in line of giving the user the option to choose how accented he wishes his "bold math" to be with respect to normal (regular) math (meaning symbols that represent vectors, matrices, …), either medium, semi bold, bold, or extra bold.

**Comment by YuanshengZhao** [comment]
I have added the extra-bold weight. However, adding the medium weight seems to be unsuitable, because it would be very difficult to distinguish normal and bold weight. Below is the effect of extra-bold, bold and semi bold.
![image](https://user-images.githubusercontent.com/37881856/42017972-39a8dcbe-7aa0-11e8-951d-4382f123530b.png)

**Comment by itzsimpl** [comment]
Great job, thank you.
