### ISSUE TITLE
Widetilde broken and tilde looks like an acute at small sizes

### ISSUE THREAD

**Issue by cluelessnessness** [YuanshengZhao/Garamond-Math#8]
The command \widetilde produces, instead of the tilde, a superposed e (see below). No idea why.
![screenshot_20181219180335](https://user-images.githubusercontent.com/42040356/50238963-ae9e8180-03b8-11e9-9fc8-d0eb0692321e.png)

Tilde is less of an issue, more of a query, since I think it looks a bit too much like an acute accent at text sizes.  Could it be changed slightly?
![screenshot_20181219180402](https://user-images.githubusercontent.com/42040356/50238965-ae9e8180-03b8-11e9-9153-2d510e971016.png)

**Comment by YuanshengZhao** [comment]
Thank you for the comment. The wide tilde should be a bug. For the tilde, it is inherited from EB Garamond though it looks a bit strange in math. @Stone-Zeng also thinks that a normal-looking one is desired.

I will resolve the issue this weekend.

**Comment by cluelessnessness** [comment]
Lovely, thank you.

**Comment by Stone-Zeng** [comment]
@cluelessnessness We can't find the issue of wild tilde. Where have you downloaded the otf file? And which engine do you use, XeTeX, LuaTeX or MS Word?

**Comment by cluelessnessness** [comment]
If I recall correctly, I downloaded the file from the github page.  I use a LaTeX engine — I think it's XeTeX?  Not sure.  Am 22.12.2018 1:42 nachm. schrieb Xiangdong Zeng <notifications@github.com>:@cluelessnessness We can't find the issue of wild tilde. Where have you downloaded the otf file? And which engine do you use, XeTeX, LuaTeX or MS Word?

**Comment by YuanshengZhao** [comment]
Could you please provide a minimal working example? On my computer, both XeTeX and LuaTeX provide correct result for the following:

```TeX
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Garamond-Math}[Path=./]
\begin{document}
\[\widetilde{y}\]
\end{document}
```
![image](https://user-images.githubusercontent.com/37881856/50376978-b67c5100-0658-11e9-9df6-cbe5b503b930.png)

**Comment by YuanshengZhao** [comment]
Normal tilde made (`StylisticSet 9`). The otf file in the branch `MetricGenTest` contains this update.
